name: Imperative PR Title Check

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

env:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

jobs:
  check-title:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Initialize Go Module
      run: go mod init pr_check

    - name: Download Dependencies
      run: go get github.com/jdkato/prose/v2

    - name: List directory for debug
      run: ls -al .github/scripts/

    - name: Debug GitHub Event
      run: echo '${{ toJson(github.event) }}'

    - name: Check PR title for imperative mood
      if: github.event_name == 'pull_request'
      run: go run .github/scripts/check-pr-title-imperative-mood.go "${{ github.event.pull_request.title }}"
